// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD24mv_Mz01Qa9s6RmRafN8U8NV5xd_OpE',
    appId: '1:361580072662:web:ce3aac4df83d2c9eb88377',
    messagingSenderId: '361580072662',
    projectId: 'esp32-1b942',
    authDomain: 'esp32-1b942.firebaseapp.com',
    storageBucket: 'esp32-1b942.appspot.com',
    measurementId: 'G-CMWTY7JD1Y',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAp1o37x7HZ1g9Sjipc_zMPLQPKEpBmGac',
    appId: '1:361580072662:android:d692824d3a7895f0b88377',
    messagingSenderId: '361580072662',
    projectId: 'esp32-1b942',
    storageBucket: 'esp32-1b942.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCigMyczFbPFbK66wSdDlGk8aheDH-_iGE',
    appId: '1:361580072662:ios:714f6178a1940b42b88377',
    messagingSenderId: '361580072662',
    projectId: 'esp32-1b942',
    storageBucket: 'esp32-1b942.appspot.com',
    iosBundleId: 'com.example.flutterApplication5',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCigMyczFbPFbK66wSdDlGk8aheDH-_iGE',
    appId: '1:361580072662:ios:714f6178a1940b42b88377',
    messagingSenderId: '361580072662',
    projectId: 'esp32-1b942',
    storageBucket: 'esp32-1b942.appspot.com',
    iosBundleId: 'com.example.flutterApplication5',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD24mv_Mz01Qa9s6RmRafN8U8NV5xd_OpE',
    appId: '1:361580072662:web:76d1bcdcc41d39a4b88377',
    messagingSenderId: '361580072662',
    projectId: 'esp32-1b942',
    authDomain: 'esp32-1b942.firebaseapp.com',
    storageBucket: 'esp32-1b942.appspot.com',
    measurementId: 'G-0C0EGDMNZN',
  );

}